import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import { SessionProvider } from 'next-auth/react';
import AuthProvider from './auth-provider';
import { Inter as FontSans } from 'next/font/google';

import { cn } from '@/lib/utils';
import { auth } from '@/auth';
import TRPCProvider from '@/app/_trpc/Provider';

const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();

	return (
		<SessionProvider session={session}>
			<TRPCProvider>
				<html lang="en">
					<body
						className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
						<AuthProvider>{children}</AuthProvider>
						{/* <Toaster /> */}
					</body>
				</html>
			</TRPCProvider>
		</SessionProvider>
	);
}
