import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import { SessionProvider } from 'next-auth/react';
import AuthProvider from './auth-provider';
import { Inter as FontSans } from 'next/font/google';
import {
	Menubar,
	MenubarContent,
	MenubarItem,
	MenubarMenu,
	MenubarSeparator,
	MenubarShortcut,
	MenubarTrigger,
} from '@/components/ui/menubar';
import { cn } from '@/lib/utils';
import { auth } from '@/auth';
import Link from 'next/link';
import TRPCProvider from '@/trpc/client/Provider';

const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();

	return (
		<SessionProvider session={session}>
			<TRPCProvider>
				<html lang="en">
					<body
						className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
						<AuthProvider>
							<Menubar>
								<MenubarMenu>
									<MenubarTrigger>
										<Link href="/test">Test</Link>
									</MenubarTrigger>
									<MenubarTrigger>
										<Link href="/other">Other</Link>
									</MenubarTrigger>
									<MenubarTrigger>
										<Link href="/">Home</Link>
									</MenubarTrigger>
									<MenubarTrigger>
										<Link href="/unit">Units</Link>
									</MenubarTrigger>
								</MenubarMenu>
							</Menubar>
							{children}
						</AuthProvider>
						{/* <Toaster /> */}
					</body>
				</html>
			</TRPCProvider>
		</SessionProvider>
	);
}
